name: scanpy-env
channels:
  - conda-forge
  - bioconda
  - anaconda
  - plotly
  - r
  - defaults
dependencies:
  - anaconda::ipykernel=5.1.4
  # scanpy
  - conda-forge::loompy=2.0.17
  - conda-forge::h5py=2.10.0
  - conda-forge::numpy=1.18.1
  - conda-forge::pandas=1.0.3
  - anaconda::xlrd=1.2.0
  - anaconda::openpyxl=3.0.3
  - bioconda::scanpy=1.4.6
  - conda-forge::leidenalg=0.8.0
  - bioconda::bbknn=1.3.9
  - plotly::plotly=4.6.0
  - conda-forge::matplotlib=3.2.1
  - conda-forge::matplotlib-venn=0.11.5
  - anaconda::networkx=2.4
  # scVI
  - bioconda::scvi=0.6.4
  - conda-forge::dataclasses=0.7
  # Palantir
  - r::r=3.6.0
  - conda-forge::r-gam=1.16.1
  - conda-forge::r-readr=1.3.1
