name: scanpy-env
channels:
  - conda-forge
  - bioconda
  - anaconda
  - plotly
  - r
  - defaults
dependencies:
  - anaconda::ipykernel=5.1.3
  - conda-forge::ipywidgets=7.5.1
  - conda-forge::nodejs=13.7.0
  - conda-forge::numpy=1.17.3
  - conda-forge::pandas=0.25.3
  - conda-forge::matplotlib=3.1.2
  - conda-forge::matplotlib-venn=0.11.5
  - conda-forge::loompy=2.0.17
  - anaconda::xlrd=1.2.0
  - conda-forge::h5py=2.9.0
  - bioconda::scanpy=1.4.4.post1
  - conda-forge::leidenalg=0.7.0
  - anaconda::openpyxl=3.0.3
  - bioconda::bbknn=1.3.7
  - plotly::plotly=4.5.4
  # Palantir
  - r::r=3.6.0
  - conda-forge::r-gam=1.16.1
  - conda-forge::r-readr=1.3.1
